name: PyTest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
      - uses: pyvista/setup-headless-display-action@v3
        with:
          qt: true
          pyvista: false
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install 3.12
      - run: uv sync --locked --python 3.12 --all-extras --dev
      - run: |
          uv run coverage run -m pytest --durations=10 --durations-min=1 -o faulthandler_timeout=120
        timeout-minutes: 10
        env:
          QT_QPA_PLATFORM: "offscreen"
      - run: uv run coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
